kind: pipeline
type: docker
name: default

steps:
  - name: build-and-push
    image: docker
    privileged: true
    volumes:
      - name: varrun
        path: /var/run
    environment:
      REGISTRY_LOGIN:
        from_secret: REGISTRY_LOGIN
      REGISTRY_PASS:
        from_secret: REGISTRY_PASS
    commands:
      - docker login -u $REGISTRY_LOGIN -p $REGISTRY_PASS
      - docker build -t eluki/jutco:latest .
      - docker push eluki/jutco:latest
    when:
      branch:
        - master

node:
  group: swarm-openvz

volumes:
  - name: varrun
    host:
      path: /var/run